[2025-02-08 15:47:27,817] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.wget scheduled__2023-02-02T06:00:00+00:00 [queued]>
[2025-02-08 15:47:27,828] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.wget scheduled__2023-02-02T06:00:00+00:00 [queued]>
[2025-02-08 15:47:27,829] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2025-02-08 15:47:27,829] {taskinstance.py:1239} INFO - Starting attempt 12 of 12
[2025-02-08 15:47:27,829] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2025-02-08 15:47:27,843] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): wget> on 2023-02-02 06:00:00+00:00
[2025-02-08 15:47:27,852] {standard_task_runner.py:52} INFO - Started process 6096 to run task
[2025-02-08 15:47:27,855] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'wget', 'scheduled__2023-02-02T06:00:00+00:00', '--job-id', '130', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmptmyyrxy1', '--error-file', '/tmp/tmpvodkhoq5']
[2025-02-08 15:47:27,858] {standard_task_runner.py:77} INFO - Job 130: Subtask wget
[2025-02-08 15:47:27,943] {logging_mixin.py:109} INFO - Running <TaskInstance: LocalIngestionDag.wget scheduled__2023-02-02T06:00:00+00:00 [running]> on host 56ce40b7c807
[2025-02-08 15:47:28,008] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2025-02-08 15:47:28,040] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=LocalIngestionDag
AIRFLOW_CTX_TASK_ID=wget
AIRFLOW_CTX_EXECUTION_DATE=2023-02-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-02T06:00:00+00:00
[2025-02-08 15:47:28,041] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2025-02-08 15:47:28,042] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sS https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2023-02.parquet > /opt/***output_2023-02.parquet"']
[2025-02-08 15:47:28,058] {subprocess.py:85} INFO - Output:
[2025-02-08 15:47:28,061] {subprocess.py:89} INFO - bash: -c: line 0: unexpected EOF while looking for matching `"'
[2025-02-08 15:47:28,062] {subprocess.py:89} INFO - bash: -c: line 1: syntax error: unexpected end of file
[2025-02-08 15:47:28,062] {subprocess.py:93} INFO - Command exited with return code 1
[2025-02-08 15:47:28,077] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-02-08 15:47:28,083] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=LocalIngestionDag, task_id=wget, execution_date=20230202T060000, start_date=20250208T154727, end_date=20250208T154728
[2025-02-08 15:47:28,097] {standard_task_runner.py:92} ERROR - Failed to execute job 130 for task wget
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-02-08 15:47:28,108] {local_task_job.py:154} INFO - Task exited with return code 1
[2025-02-08 15:47:28,153] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
